version: '3.8'
services:
  db:
    container_name: postgresdb
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ./web/.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    container_name: api
    restart: always
    build: ./api
    ports:
      - "8001:8001"
    volumes:
      - ./api:/home/app/web
    command: uvicorn main:app --reload --proxy-headers --host 0.0.0.0 --port 8001
    depends_on:
      - db
  django:
    container_name: webapp
    env_file:
      - ./web/.env
    environment:
      DEBUG: 1
      GUNICORN_BIND_ADDRESS: 0.0.0.0:8000
    restart: always
    build: ./web
    ports:
      - "8000:8000"
    volumes:
      - ./web:/app
    command: ./manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
