version: '3.8'
services:
  api-django:
    container_name: web-api
    image: acrusba.azurecr.io/web-api
    platform: linux/amd64
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - "8001:8001"

  web-django:
    container_name: web-django
    image: acrusba.azurecr.io/web-django
    platform: linux/amd64
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
