# Generated by Django 4.2.10 on 2024-03-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApprovalDate', models.DateField(verbose_name='Approval Date')),
                ('Term', models.IntegerField(verbose_name='Loan term in months')),
                ('NoEmp', models.IntegerField(verbose_name='Number of business employees')),
                ('FranchiseCode', models.CharField(max_length=100, verbose_name='Are you a franchisee ?')),
                ('ApprovalFy', models.IntegerField(verbose_name='Fiscal year of commitment')),
                ('NewExist', models.CharField(max_length=100, verbose_name='New if it has existed for less than two years')),
                ('LowDoc', models.CharField(max_length=100, verbose_name='Do you have a Loan Program ?')),
                ('GrAppv', models.IntegerField(verbose_name='What is the gross amount of the loan approved by the bank ?')),
                ('CreateJob', models.IntegerField(verbose_name='Have you generated job creation ?')),
                ('RetainedJob', models.IntegerField(verbose_name='Have any jobs been retained ?')),
                ('UrbanRural', models.CharField(max_length=100, verbose_name='Are you located in a rural or urban area ?')),
                ('RevLineCr', models.CharField(max_length=100, verbose_name='Is a revolving line of credit available ?')),
            ],
        ),
    ]
