# Generated by Django 4.2.11 on 2024-03-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_modelapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelapi',
            name='ApprovalDate',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='modelapi',
            name='ApprovalFy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='modelapi',
            name='CreateJob',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='modelapi',
            name='FranchiseCode',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='modelapi',
            name='GrAppv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='modelapi',
            name='LowDoc',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='modelapi',
            name='NewExist',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='modelapi',
            name='NoEmp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='modelapi',
            name='RetainedJob',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='modelapi',
            name='RevLineCr',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='modelapi',
            name='Term',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='modelapi',
            name='UrbanRural',
            field=models.CharField(),
        ),
    ]
