# Generated by Django 4.2.11 on 2024-03-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_modelapi_approvaldate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelapi',
            old_name='ApprovalFy',
            new_name='ApprovalFY',
        ),
        migrations.AddField(
            model_name='modelapi',
            name='Naics',
            field=models.CharField(blank=True, null=True),
        ),
    ]
