# Generated by Django 4.2.11 on 2024-03-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_approvalfy_modelapi_approvalfy_modelapi_naics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelapi',
            name='ApprovalDate',
            field=models.DateField(),
        ),
    ]
