# Generated by Django 4.2.11 on 2024-03-07 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
