# Generated by Django 4.2.11 on 2024-03-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_user_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
    ]
